name: CI

# set when this workflow runs
on:
  # on all pushes to main
  push:
    branches:
    - main

  # on all PR pushes
  pull_request:
    types:
    - opened
    - synchronize

jobs:
  build-test-ubuntu-stack:
    runs-on: ubuntu-latest
    name: Ubuntu / Stack
    steps:
    - uses: actions/checkout@v2

    # relative paths are relative to the project directory
    - name: Cache Stack build artifacts (user + project)
      uses: actions/cache@v2
      with:
        path: |
          ~/.stack
          .stack-work
        # best effort for cache: tie it to Stack resolver and package config
        key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml.lock', 'package.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack

    - name: Install project dependencies
      run: stack --no-terminal test --only-dependencies

    - name: Build and run tests
      run: stack --no-terminal haddock --test --no-haddock-deps
