name: Test

on:
  push:
    branches:
    - main
  pull_request:
    types:
    - synchronize
    - opened
    - reopened

jobs:
  test:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
    runs-on: ${{ matrix.os }}
    name: Test (${{ matrix.os }})

    steps:
    - uses: actions/checkout@v3

    - name: Setup Haskell build environment
      uses: haskell/actions/setup@v2
      with:
        ghc-version: "9.0"

    - name: Install project dependencies
      run: cabal test --test-show-details=streaming
